import { ProjectList } from "@/components/project-list";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Projects",
  description: "A list of some serious projects I've worked on.",
};

export default function Projects() {
  const orders = [
    {
      name: "Kelbet Til",
      description:
        "all school literature in one place with qr codes and a built-in pdf reader.",
      href: "https://kelbet-til.vercel.app",
      tag: "70K KZT",
    },
    {
      name: "NIS PM Almaty Website",
      description:
        "the official website of my school. it has articles, dynamic pages and multilingual support.",
      href: "https://fmalmnis.vercel.app",
      tag: "it's my school",
    },
  ];

  const hackathons = [
    {
      name: "aigul",
      description:
        "create a roadmap for any skill you want to acquire. generated by ai.",
      href: "https://aigul-web.vercel.app",
      tag: "1st place",
    },
  ];

  return (
    <section>
      <div className="flex items-center justify-center">
        <Tabs defaultValue="orders" className="w-full">
          <div className="flex items-center justify-between">
            <h1 className="text-2xl">Projects</h1>
            <TabsList>
              <TabsTrigger value="orders">Orders</TabsTrigger>
              <TabsTrigger value="hackathons">Hackathons</TabsTrigger>
            </TabsList>
          </div>
          <TabsContent value="orders">
            <ProjectList projects={orders} />
          </TabsContent>
          <TabsContent value="hackathons">
            <ProjectList projects={hackathons} />
          </TabsContent>
        </Tabs>
      </div>
    </section>
  );
}
